### ISSUE TITLE
please follow git commit message convention

### ISSUE THREAD

**Issue by KYankee6** [ChickenRushKR/mmWave-Path-Loss-Modeling-for-5G-Communications-in-Dense-Urban-Scenarios#1]
Dear @ChickenRushKR 
[git message convetion](https://github.com/kazupon/git-commit-message-convention)
thanks in advance.
👍

**Comment by ChickenRushKR** [comment]
one step to the moon

**Comment by ChickenRushKR** [comment]
> Dear @ChickenRushKR 
> 
> [git message convetion](https://github.com/kazupon/git-commit-message-convention)
> 
> thanks in advance.
> 
> 👍

one step towards the moon
